image:
  repository: ghcr.io/wyrihaximusnet/kubernetes-redis-db-assignment-operator
  tag: 2025.01.16
  pullPolicy: IfNotPresent

resources:
  # Setting this pretty low since this is a low resource intensive application, increase when needed
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
